#!/usr/bin/env python
from setup_utils import *
import os

# idav.server
def undeploy():
    app = actions.getAppName("idav")
    if app: actions.undeploy(app) 
    
actions, arg, props = getActions("idav-setup.properties", [])

prop_name = "idav.properties"
prop_list = []


if arg in ["CONFIGURE", "INSTALL"]:
    
    actions.checkNoErrors()
    
if arg == "INSTALL":   
    properties = getProperties(prop_name,prop_list)             
           
    actions.installFile(prop_name)
    
    try:
        undeploy()
        actions.deploy(deploymentorder=120)
        app = actions.getAppName("icat.server")
        if app: actions.restartApp(app)
    except Exception, e:
        abort(str(e))
               
if arg == "UNINSTALL":
    actions.removeFile(prop_name)
    
    try:
        undeploy() 
    except Exception, e:
        abort(str(e)) 
